name: Sync to Hugging Face Space

on:
  push:
    paths-ignore:
      - 'rag_db/**'  
    branches:
      - main  # O la rama que desees sincronizar

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para clonar todo el historial
          lfs: true  # Ensure LFS files are fetched

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs fetch --all
          git lfs checkout
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"          

      - name: Handle missing LFS files
        run: |
          # Check if LFS files exist and handle missing ones
          if ! git lfs ls-files --name-only | xargs -I {} test -f {}; then
            echo "Some LFS files are missing, configuring to allow incomplete push"
            git config lfs.allowincompletepush true
          fi
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |        
          # Añadir el repositorio de Hugging Face como remoto
          git remote add hf https://USER_NAME:$HF_TOKEN@huggingface.co/spaces/EuclidesHernandez/HF_GAIA_AGENT
          
          # Forzar push al repositorio de Hugging Face
          git push -f hf main:main        
