name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main  # O la rama que desees sincronizar
    paths-ignore:
      - 'rag_db/**'

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para clonar todo el historial
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # No hacer check de archivos faltantes
          git config lfs.allowincompletepush true
          # Añadir el repositorio de Hugging Face como remoto
          git remote add hf https://USER_NAME:$HF_TOKEN@huggingface.co/spaces/EuclidesHernandez/HF_GAIA_AGENT
          
          # Forzar push al repositorio de Hugging Face
          git push -f hf main:main        
